(function initAssignment5SceneData(globalScope) {
  const TEXTURES = {
    grass: "assets/textures/grass.svg",
    stone: "assets/textures/stone.svg",
    spirit: "assets/textures/spirit.svg",
    wood: "assets/textures/wood.svg",
  };

  const SKYBOX_FACES = [
    "assets/skybox/px.svg",
    "assets/skybox/nx.svg",
    "assets/skybox/py.svg",
    "assets/skybox/ny.svg",
    "assets/skybox/pz.svg",
    "assets/skybox/nz.svg",
  ];

  const MATERIALS = {
    bark: { color: "#76513a", roughness: 0.88 },
    ember: { color: "#f59e0b", emissive: "#f97316", emissiveIntensity: 0.45 },
    leafA: { color: "#4f8a43", roughness: 0.82 },
    leafB: { color: "#26735f", roughness: 0.78 },
    moss: { color: "#6f8f4e", roughness: 0.9 },
    portal: { color: "#7dd3fc", emissive: "#38bdf8", emissiveIntensity: 0.65 },
    roof: { color: "#7c3f2c", roughness: 0.76 },
    shrine: { color: "#b26b3b", roughness: 0.74 },
    spirit: {
      color: "#fef3c7",
      emissive: "#67e8f9",
      emissiveIntensity: 1.1,
      transparent: true,
      opacity: 0.92,
    },
    stone: { color: "#87919a", roughness: 0.86 },
  };

  const PRIMARY_OBJECTS = [
    {
      id: "ground-floor",
      geometry: "box",
      materialKey: "moss",
      textureKey: "grass",
      position: [0, -0.08, 0],
      scale: [28, 0.16, 24],
      receiveShadow: true,
    },
    {
      id: "shrine-base",
      geometry: "box",
      materialKey: "shrine",
      textureKey: "wood",
      position: [0, 0.45, -6.5],
      scale: [3.8, 0.9, 2.2],
      castShadow: true,
      receiveShadow: true,
    },
    {
      id: "shrine-back",
      geometry: "box",
      materialKey: "shrine",
      textureKey: "wood",
      position: [0, 1.45, -7.2],
      scale: [3.2, 1.6, 0.35],
      castShadow: true,
    },
    {
      id: "shrine-roof",
      geometry: "cone",
      materialKey: "roof",
      position: [0, 2.55, -7.05],
      rotation: [0, Math.PI / 4, 0],
      scale: [2.5, 1.1, 2.5],
      castShadow: true,
    },
    {
      id: "altar-step-front",
      geometry: "box",
      materialKey: "stone",
      textureKey: "stone",
      position: [0, 0.14, -4.9],
      scale: [4.6, 0.28, 0.7],
      castShadow: true,
      receiveShadow: true,
    },
    {
      id: "altar-step-middle",
      geometry: "box",
      materialKey: "stone",
      textureKey: "stone",
      position: [0, 0.3, -5.45],
      scale: [3.7, 0.32, 0.7],
      castShadow: true,
      receiveShadow: true,
    },
    {
      id: "portal-ring",
      geometry: "torus",
      materialKey: "portal",
      position: [0, 2.0, -6.4],
      rotation: [Math.PI / 2, 0, 0],
      scale: [1.2, 1.2, 1.2],
      animation: "portalSpin",
      castShadow: true,
    },
    {
      id: "left-lantern-post",
      geometry: "cylinder",
      materialKey: "bark",
      textureKey: "wood",
      position: [-2.7, 0.95, -5.4],
      scale: [0.22, 1.9, 0.22],
      castShadow: true,
    },
    {
      id: "right-lantern-post",
      geometry: "cylinder",
      materialKey: "bark",
      textureKey: "wood",
      position: [2.7, 0.95, -5.4],
      scale: [0.22, 1.9, 0.22],
      castShadow: true,
    },
    {
      id: "left-lantern-cap",
      geometry: "box",
      materialKey: "ember",
      position: [-2.7, 1.98, -5.4],
      scale: [0.55, 0.4, 0.55],
      animation: "gentleBob",
      castShadow: true,
    },
    {
      id: "right-lantern-cap",
      geometry: "box",
      materialKey: "ember",
      position: [2.7, 1.98, -5.4],
      scale: [0.55, 0.4, 0.55],
      animation: "gentleBob",
      castShadow: true,
    },
    {
      id: "flame-north",
      geometry: "sphere",
      materialKey: "spirit",
      textureKey: "spirit",
      position: [0, 1.15, -2.2],
      scale: [0.34, 0.34, 0.34],
      animation: "spiritPulse",
      collectible: true,
      castShadow: true,
    },
    {
      id: "flame-east",
      geometry: "sphere",
      materialKey: "spirit",
      textureKey: "spirit",
      position: [5.2, 1.1, -1.4],
      scale: [0.34, 0.34, 0.34],
      animation: "spiritPulse",
      collectible: true,
      castShadow: true,
    },
    {
      id: "flame-south",
      geometry: "sphere",
      materialKey: "spirit",
      textureKey: "spirit",
      position: [-1.4, 1.1, 5.4],
      scale: [0.34, 0.34, 0.34],
      animation: "spiritPulse",
      collectible: true,
      castShadow: true,
    },
    {
      id: "flame-west",
      geometry: "sphere",
      materialKey: "spirit",
      textureKey: "spirit",
      position: [-5.5, 1.15, -0.5],
      scale: [0.34, 0.34, 0.34],
      animation: "spiritPulse",
      collectible: true,
      castShadow: true,
    },
    {
      id: "flame-hidden",
      geometry: "sphere",
      materialKey: "spirit",
      textureKey: "spirit",
      position: [3.8, 1.25, 4.6],
      scale: [0.34, 0.34, 0.34],
      animation: "spiritPulse",
      collectible: true,
      castShadow: true,
    },
    {
      id: "tree-a-trunk",
      geometry: "cylinder",
      materialKey: "bark",
      textureKey: "wood",
      position: [-8.5, 0.85, -6.8],
      scale: [0.35, 1.7, 0.35],
      castShadow: true,
    },
    {
      id: "tree-a-crown",
      geometry: "cone",
      materialKey: "leafA",
      position: [-8.5, 2.25, -6.8],
      scale: [1.4, 2.0, 1.4],
      castShadow: true,
    },
    {
      id: "tree-b-trunk",
      geometry: "cylinder",
      materialKey: "bark",
      textureKey: "wood",
      position: [7.8, 0.85, -6.1],
      scale: [0.38, 1.7, 0.38],
      castShadow: true,
    },
    {
      id: "tree-b-crown",
      geometry: "sphere",
      materialKey: "leafB",
      position: [7.8, 2.2, -6.1],
      scale: [1.45, 1.25, 1.45],
      castShadow: true,
    },
    {
      id: "tree-c-trunk",
      geometry: "cylinder",
      materialKey: "bark",
      textureKey: "wood",
      position: [-8.4, 0.75, 3.9],
      scale: [0.3, 1.5, 0.3],
      castShadow: true,
    },
    {
      id: "tree-c-crown",
      geometry: "cone",
      materialKey: "leafA",
      position: [-8.4, 2.05, 3.9],
      scale: [1.25, 1.85, 1.25],
      castShadow: true,
    },
    {
      id: "tree-d-trunk",
      geometry: "cylinder",
      materialKey: "bark",
      textureKey: "wood",
      position: [8.6, 0.8, 3.4],
      scale: [0.32, 1.6, 0.32],
      castShadow: true,
    },
    {
      id: "tree-d-crown",
      geometry: "sphere",
      materialKey: "leafB",
      position: [8.6, 2.15, 3.4],
      scale: [1.35, 1.2, 1.35],
      castShadow: true,
    },
    {
      id: "tree-e-trunk",
      geometry: "cylinder",
      materialKey: "bark",
      textureKey: "wood",
      position: [-4.7, 0.72, 7.2],
      scale: [0.28, 1.45, 0.28],
      castShadow: true,
    },
    {
      id: "tree-e-crown",
      geometry: "cone",
      materialKey: "leafA",
      position: [-4.7, 1.95, 7.2],
      scale: [1.15, 1.75, 1.15],
      castShadow: true,
    },
    {
      id: "tree-f-trunk",
      geometry: "cylinder",
      materialKey: "bark",
      textureKey: "wood",
      position: [5.6, 0.72, 7.0],
      scale: [0.28, 1.45, 0.28],
      castShadow: true,
    },
    {
      id: "tree-f-crown",
      geometry: "cone",
      materialKey: "leafB",
      position: [5.6, 1.95, 7.0],
      scale: [1.15, 1.75, 1.15],
      castShadow: true,
    },
    {
      id: "path-stone-1",
      geometry: "cylinder",
      materialKey: "stone",
      textureKey: "stone",
      position: [0, 0.06, 3.8],
      scale: [0.72, 0.12, 0.72],
      castShadow: true,
      receiveShadow: true,
    },
    {
      id: "path-stone-2",
      geometry: "cylinder",
      materialKey: "stone",
      textureKey: "stone",
      position: [0.35, 0.06, 2.55],
      scale: [0.65, 0.12, 0.65],
      castShadow: true,
      receiveShadow: true,
    },
    {
      id: "path-stone-3",
      geometry: "cylinder",
      materialKey: "stone",
      textureKey: "stone",
      position: [-0.2, 0.06, 1.3],
      scale: [0.68, 0.12, 0.68],
      castShadow: true,
      receiveShadow: true,
    },
    {
      id: "path-stone-4",
      geometry: "cylinder",
      materialKey: "stone",
      textureKey: "stone",
      position: [0.28, 0.06, 0.05],
      scale: [0.7, 0.12, 0.7],
      castShadow: true,
      receiveShadow: true,
    },
    {
      id: "path-stone-5",
      geometry: "cylinder",
      materialKey: "stone",
      textureKey: "stone",
      position: [-0.25, 0.06, -1.25],
      scale: [0.66, 0.12, 0.66],
      castShadow: true,
      receiveShadow: true,
    },
    {
      id: "path-stone-6",
      geometry: "cylinder",
      materialKey: "stone",
      textureKey: "stone",
      position: [0.1, 0.06, -2.95],
      scale: [0.78, 0.12, 0.78],
      castShadow: true,
      receiveShadow: true,
    },
  ];

  const LIGHTS = [
    {
      id: "soft-ambient",
      type: "AmbientLight",
      color: "#cbd5e1",
      intensity: 0.45,
    },
    {
      id: "moon-directional",
      type: "DirectionalLight",
      color: "#f8fafc",
      intensity: 1.6,
      position: [-5, 9, 4],
      target: [0, 0, -3],
      castShadow: true,
    },
    {
      id: "sky-hemisphere",
      type: "HemisphereLight",
      skyColor: "#9cc9ff",
      groundColor: "#3d2b1f",
      intensity: 0.75,
    },
    {
      id: "shrine-point",
      type: "PointLight",
      color: "#fbbf24",
      intensity: 3.2,
      distance: 14,
      position: [0, 2.2, -5.8],
      animation: "lightPulse",
    },
    {
      id: "path-spot",
      type: "SpotLight",
      color: "#a7f3d0",
      intensity: 2.2,
      distance: 20,
      angle: 0.42,
      penumbra: 0.45,
      position: [0, 7.5, 4],
      target: [0, 0, -2.5],
      castShadow: true,
    },
  ];

  const MODEL_ASSET = {
    id: "poly-pizza-fox",
    path: "assets/models/fox/fox.glb",
    textured: true,
    textureFallbackKey: "spirit",
    credit: "Fox by Poly by Google on Poly Pizza, CC-BY 3.0",
    sourceUrl: "https://poly.pizza/m/10u8FYPC5Br",
    position: [-2.2, 0.05, -3.15],
    rotation: [0, Math.PI / 4, 0],
    scale: [0.018, 0.018, 0.018],
  };

  const CAMERA = {
    fov: 55,
    near: 0.1,
    far: 120,
    position: [7.8, 5.0, 10.5],
    target: [0, 1.3, -2.8],
  };

  const WOW_FEATURE = {
    note: "Wow: click the glowing spirit flames to collect them and awaken the shrine with a spirit beam, pulsing rings, and floating sparks.",
    collectibleCount: PRIMARY_OBJECTS.filter((object) => object.collectible).length,
    awakenedStatus: "Shrine awakened: a spirit beam, pulsing rings, and floating sparks fill the grove.",
    awakenedEffects: [
      "spirit beam",
      "pulsing shrine rings",
      "floating sparks",
      "brighter portal glow",
    ],
  };

  function deepFreeze(value) {
    if (!value || typeof value !== "object" || Object.isFrozen(value)) {
      return value;
    }

    Object.values(value).forEach(deepFreeze);
    return Object.freeze(value);
  }

  const api = deepFreeze({
    CAMERA,
    LIGHTS,
    MATERIALS,
    MODEL_ASSET,
    PRIMARY_OBJECTS,
    SKYBOX_FACES,
    TEXTURES,
    WOW_FEATURE,
  });

  if (typeof module !== "undefined" && module.exports) {
    module.exports = api;
  }

  globalScope.ASSIGNMENT5_SCENE = api;
}(typeof globalThis !== "undefined" ? globalThis : this));
